"""
Tests for Admin Test Agent agent

Generated by the permissioned creation system.
"""

import unittest
from unittest.mock import Mock, patch
import sys
import os

# Add the parent directory to sys.path to allow imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.admin_test_agent import admin_test_agent


class TestAdminTestAgent(unittest.TestCase):
    """Test cases for Admin Test Agent agent"""

    def setUp(self):
        """Set up test fixtures"""
        pass

    def test_agent_creation(self):
        """Test that the agent can be created and called"""
        task = "Test task for Admin Test Agent"
        result = admin_test_agent(task)

        self.assertIsInstance(result, dict)
        self.assertIn("status", result)
        self.assertIn("result", result)
        self.assertIn("message", result)

    def test_successful_execution(self):
        """Test successful task execution"""
        task = "Perform a simple test operation"
        result = admin_test_agent(task)

        # Should return a valid response structure
        self.assertIsInstance(result, dict)
        self.assertIn("status", result)
        self.assertIn("message", result)

    def test_error_handling(self):
        """Test error handling with invalid input"""
        task = ""  # Empty task should be handled gracefully
        result = admin_test_agent(task)

        self.assertIsInstance(result, dict)
        self.assertIn("status", result)
        self.assertIn("message", result)

    def test_capabilities(self):
        """Test that the agent has the expected capabilities"""
        # Test that the agent can handle tasks related to its capabilities
        capabilities = ["admin_test"]

        for capability in capabilities:
            task = f"Test {capability.lower()} capability"
            result = admin_test_agent(task)

            self.assertIsInstance(result, dict)
            self.assertIn("status", result)

    @patch("agents.admin_test_agent.utils.all_tool_functions")
    def test_tool_integration(self, mock_tools):
        """Test integration with tools"""
        # Mock available tools
        mock_tools.return_value = []

        task = "Test tool integration"
        result = admin_test_agent(task)

        self.assertIsInstance(result, dict)
        self.assertIn("status", result)

    def test_memory_integration(self):
        """Test integration with memory system"""
        task = "Test memory integration"
        result = admin_test_agent(task)

        self.assertIsInstance(result, dict)
        self.assertIn("status", result)


if __name__ == "__main__":
    unittest.main()
